apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.7-0
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          TimeZone: "Asia/Riyadh"
          max_connections: "500"
        pg_hba:
          - "hostnossl all all 0.0.0.0/0 trust" # this line enabled logical replication with programmatic access
          - "local all all trust"
          - "host all all ::1/128 trust"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.40-1
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
  users:
  - name: 'hippo'
    databases:
      - hippo

